// Package plugin defines the Plugin interface and the Operation type that
// plugins return. Plugins never touch the filesystem directly — they read a
// model.Project and return []Operation; the engine handles all IO, conflict
// resolution, and lockfile bookkeeping.
package plugin

import (
	"fmt"
	"io/fs"

	"agents.dev/agents/internal/model"
)

// OpKind is the type of filesystem operation an Operation represents.
type OpKind string

const (
	OpWrite   OpKind = "write"   // create or overwrite a file
	OpSymlink OpKind = "symlink" // create a symlink (Source field points at target)
	OpAppend  OpKind = "append"  // append content to a file (creates if absent)
	OpMerge   OpKind = "merge"   // structural merge (e.g., JSON settings.json) — plugin produces fully-merged content
	OpDelete  OpKind = "delete"  // remove a file previously generated by this plugin
)

// Mode is the sync mode requested for an Operation. The engine may downgrade
// (e.g., symlink → write on Windows or when transformation is needed).
type Mode string

const (
	ModeWrite   Mode = "write"
	ModeSymlink Mode = "symlink"
	ModeHook    Mode = "hook" // generated lazily by a session hook; gitignored
)

// Operation is a single planned filesystem mutation.
type Operation struct {
	// Kind is what to do.
	Kind OpKind
	// Path is the target path relative to the project root.
	Path string
	// Content is the bytes to write (for Write/Append/Merge).
	Content string
	// LinkTarget is the path the symlink should point at (relative to Path's directory).
	// Only used when Kind == OpSymlink.
	LinkTarget string
	// FileMode for Write operations. Zero means 0644.
	FileMode fs.FileMode
	// Mode is the sync mode the plugin requested.
	Mode Mode
	// Sources are the .agents/-relative paths that produced this Operation
	// (for traceability via `agents which`).
	Sources []string
	// Plugin is the name of the plugin that emitted this Operation.
	Plugin string
	// Warnings are degradation notes attached to this Operation.
	Warnings []Warning
	// Merger, when non-nil and Kind == OpMerge, is called by the engine with
	// the existing file's bytes (nil if the file doesn't exist) and returns
	// the merged content the engine should write. Plugins setting Merger
	// MUST NOT pre-read the target file in Plan() — that I/O belongs to the
	// engine, which keeps Plan pure and testable. Content is ignored when
	// Merger is set.
	Merger func(existing []byte) (string, error)
}

// Warning is a degradation note from a plugin: something in the canonical
// model is being approximated or dropped in projection.
type Warning struct {
	// Source is the .agents/-relative path of the canonical input.
	Source string
	// Message is a human-readable description of what degraded.
	Message string
	// Severity is "info", "warn", or "error".
	Severity string
}

// Support describes how a plugin handles a particular canonical capability.
//
// v0.8 carries the coarse Support enum on Capabilities; v2 (SPEC §6.2)
// replaces it with per-field FieldCapabilities. For Phase 0 both shapes
// coexist on Capabilities — see FieldSupport / FieldCapabilities below.
type Support string

const (
	SupportNative      Support = "native"      // 1:1 mapping
	SupportDegraded    Support = "degraded"    // approximated; some semantics lost
	SupportUnsupported Support = "unsupported" // not emitted at all
)

// FieldSupport describes how a plugin handles a single canonical field
// (SPEC §6.2). Distinct from Support because v2 adds the "silent" tier
// (drop without warning).
type FieldSupport string

const (
	// FieldNative — 1:1 mapping. No warning emitted.
	FieldNative FieldSupport = "native"
	// FieldDegraded — lossy mapping; one info warning per touched source.
	FieldDegraded FieldSupport = "degraded"
	// FieldUnsupported — the field is dropped; one warn-level warning per
	// touched source.
	FieldUnsupported FieldSupport = "unsupported"
	// FieldSilent — the field is dropped because it has no semantic meaning
	// on this target; no warning emitted.
	FieldSilent FieldSupport = "silent"
)

// FieldCapabilities describes the support for one primitive's fields.
//
// Supported is false when the WHOLE primitive is dropped (e.g. Windsurf
// has no Agent primitive). Fields maps canonical field paths
// (dot-notation, e.g. "Activation.Globs") to FieldSupport. Absent fields
// are assumed FieldNative. Extensions lists the extension namespaces this
// plugin reads under `extensions.<name>:` — typically just `[Name()]`.
type FieldCapabilities struct {
	Supported  bool
	Fields     map[string]FieldSupport
	Extensions []string
}

// FlatFromSupport lifts a v0.8 coarse Support value into a v2
// FieldCapabilities entry. The Supported flag is true unless the source
// Support is Unsupported; the Fields map carries a single wildcard key
// ("*") mapped to the equivalent FieldSupport tier. Plugins that have not
// yet been refined to per-field declarations can populate their v2
// FieldCapabilities cells via this helper without changing behavior; the
// engine (when it later consults per-field cells) can fall back to "*"
// for any field path it doesn't find an explicit entry for.
//
// Phase 0 callers may use this freely; subsequent phases will replace
// the wildcard entries with explicit per-field maps.
func FlatFromSupport(s Support) FieldCapabilities {
	var fs FieldSupport
	switch s {
	case SupportNative:
		fs = FieldNative
	case SupportDegraded:
		fs = FieldDegraded
	case SupportUnsupported:
		fs = FieldUnsupported
	default:
		fs = FieldNative
	}
	return FieldCapabilities{
		Supported: s != SupportUnsupported,
		Fields:    map[string]FieldSupport{"*": fs},
	}
}

// Capabilities describes what a plugin can express in its target tool.
// Used to surface degradation warnings and power `agents capabilities`.
//
// v0.8 fields (Context, ScopePaths, ..., MCP) carry coarse per-primitive
// Support values. v2 (SPEC §6.2) adds per-primitive FieldCapabilities
// under new field names so callers reading either shape compile against
// the same struct. Plugins populate both for Phase 0; later phases will
// retire the coarse v0.8 cells.
type Capabilities struct {
	Context       Support
	ScopePaths    Support
	ScopeSemantic Support
	Skills        Support
	Commands      Support
	Agents        Support
	Hooks         Support
	Permissions   Support
	MCP           Support

	// v2 per-primitive FieldCapabilities (SPEC §6.2). Named distinctly
	// from the v0.8 fields above so no collision occurs.
	AgentFields       FieldCapabilities
	SkillFields       FieldCapabilities
	CommandFields     FieldCapabilities
	HookFields        FieldCapabilities
	MCPServerFields   FieldCapabilities
	PermissionsFields FieldCapabilities
	ScopeFields       FieldCapabilities
}

// Plugin is the interface every projection plugin implements.
//
// The lifecycle: the engine calls Detect to decide whether to load the
// plugin, then Plan with the parsed model.Project. Plan must be pure —
// no filesystem mutations, no network. The engine applies the returned
// Operations and writes the lockfile.
type Plugin interface {
	// Name is the stable identifier (e.g., "claude", "cursor", "agents-md").
	Name() string

	// Detect returns true if this plugin should be active for the project at root.
	// Implementations look for marker files/directories (e.g., .claude/, .cursor/).
	Detect(root string) bool

	// Capabilities returns the plugin's capability matrix entry.
	Capabilities() Capabilities

	// Plan produces the Operations needed to project Project into this plugin's
	// target tool. It must be pure with respect to the filesystem.
	Plan(proj *model.Project, opts model.TargetOption) ([]Operation, error)

	// SchemaVersion returns the canonical schema major version this plugin
	// understands. In-tree plugins always return version.SchemaVersion; the
	// engine refuses to load any plugin whose declared version predates the
	// project's `schema_version:` (SPEC §6.4).
	SchemaVersion() int
}

// Registry holds the set of plugins available to the engine.
type Registry struct {
	plugins map[string]Plugin
}

// NewRegistry creates an empty Registry.
func NewRegistry() *Registry {
	return &Registry{plugins: make(map[string]Plugin)}
}

// Register adds a plugin. Returns an error if a plugin with the same name is
// already registered. Callers that build the registry statically typically
// ignore the error with `_ =`; the error path exists so tests and callers
// constructing the registry dynamically can detect duplicate registration
// without panicking.
func (r *Registry) Register(p Plugin) error {
	if _, exists := r.plugins[p.Name()]; exists {
		return fmt.Errorf("plugin: %q already registered", p.Name())
	}
	r.plugins[p.Name()] = p
	return nil
}

// Get returns the plugin with the given name, or nil if absent.
func (r *Registry) Get(name string) Plugin {
	return r.plugins[name]
}

// All returns all registered plugins (order not guaranteed; callers should sort if needed).
func (r *Registry) All() []Plugin {
	out := make([]Plugin, 0, len(r.plugins))
	for _, p := range r.plugins {
		out = append(out, p)
	}
	return out
}

// Names returns the names of all registered plugins.
func (r *Registry) Names() []string {
	out := make([]string, 0, len(r.plugins))
	for n := range r.plugins {
		out = append(out, n)
	}
	return out
}
