package plugins

import (
	"fmt"
	"sort"
	"strings"

	"agents.dev/agents/internal/model"
	"agents.dev/agents/internal/plugin"
)

// AgentsMDPlugin projects a model.Project into a single AGENTS.md file at the
// project root. AGENTS.md is the flat-file cross-tool standard read by Cursor,
// Codex, recent Claude Code, Aider, and others. There is no native scoping
// support — the file is always loaded in its entirety — so scopes are emitted
// as documented section headers that smarter readers can use to skip
// irrelevant material.
//
// Beyond context and scopes, the plugin also documents Skills, Slash commands,
// Subagents, Hooks, Permissions, and MCP servers as plain markdown sections.
// AGENTS.md-only tools cannot execute any of these — every such section is
// informational and carries a degradation warning.
type AgentsMDPlugin struct{}

// NewAgentsMD returns a fresh AgentsMDPlugin.
//
// Named NewAgentsMD rather than New because the plugins package has multiple
// plugin constructors and Go does not allow function-name overloading.
func NewAgentsMD() *AgentsMDPlugin {
	return &AgentsMDPlugin{}
}

// Name is the stable plugin identifier.
func (p *AgentsMDPlugin) Name() string {
	return "agents-md"
}

// Detect always returns true: most modern coding agents read AGENTS.md, and we
// produce it as the safest fallback regardless of which other plugins are
// active.
func (p *AgentsMDPlugin) Detect(root string) bool {
	return true
}

// Capabilities returns the capability matrix entry for AGENTS.md.
//
// Everything beyond Context is degraded: scopes lose enforcement (loaded
// always), and skills/commands/agents/hooks/permissions/MCP are all rendered
// as informational text. The text is preserved faithfully, but the runtime
// semantics — script execution, command invocation, hook firing, permission
// enforcement, MCP wiring — cannot be reproduced by AGENTS.md alone.
func (p *AgentsMDPlugin) Capabilities() plugin.Capabilities {
	return plugin.Capabilities{
		Context:       plugin.SupportNative,
		ScopePaths:    plugin.SupportDegraded, // becomes documented sections; loaded always
		ScopeSemantic: plugin.SupportDegraded,
		Skills:        plugin.SupportDegraded,
		Commands:      plugin.SupportDegraded,
		Agents:        plugin.SupportDegraded,
		Hooks:         plugin.SupportDegraded,
		Permissions:   plugin.SupportDegraded,
		MCP:           plugin.SupportDegraded,
	}
}

// generatedHeader is the banner emitted at the top of every AGENTS.md so
// readers (human and machine) know the file is derived from .agents/.
const generatedHeader = "<!-- Generated by agents. Do not edit by hand; edit .agents/ instead. -->"

// Plan produces a single Operation that writes AGENTS.md at the project root.
//
// Section order (each is skipped when its source slice/map is empty):
//
//  1. Generated-by header
//  2. Root context body
//  3. Scopes (## When working in <path>)
//  4. Skills (## Skills, with ### <name> entries)
//  5. Slash commands (## Slash commands, with ### /<name> entries)
//  6. Subagents (## Subagents, with ### @<name> entries)
//  7. Hooks (## Hooks, bulleted)
//  8. Permissions (## Permissions, allow/deny/ask lines)
//  9. MCP servers (## MCP servers, bulleted)
//
// Scopes, skills, commands, agents, and MCP servers are sorted by Name/Path
// so the output is byte-stable across runs.
func (p *AgentsMDPlugin) Plan(proj *model.Project, opts model.TargetOption) ([]plugin.Operation, error) {
	// Validate Mode early — AGENTS.md is always write mode, no symlink option.
	// Empty string means "default", which we treat as write.
	if opts.Mode != "" && opts.Mode != "write" {
		return nil, fmt.Errorf("agents-md: unknown mode %q (want \"write\")", opts.Mode)
	}

	var sources []string
	var warnings []plugin.Warning

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n")

	// 1. Root context body.
	if proj.Context != nil {
		body := strings.TrimSpace(proj.Context.Body)
		if body != "" {
			b.WriteString("\n")
			b.WriteString(body)
			b.WriteString("\n")
		}
		if src := relAgentsMDSource(proj, proj.Context.SourcePath); src != "" {
			sources = append(sources, src)
		}
	}

	// 2. Scopes. Sort by Path for stable, lexicographic output.
	scopes := make([]*model.Scope, 0, len(proj.Scopes))
	for _, sc := range proj.Scopes {
		if sc == nil || sc.Document == nil {
			continue
		}
		scopes = append(scopes, sc)
	}
	sort.SliceStable(scopes, func(i, j int) bool {
		return scopes[i].Path < scopes[j].Path
	})

	for _, sc := range scopes {
		// Separator between root context (or previous scope) and this scope.
		b.WriteString("\n---\n\n")
		b.WriteString("## When working in ")
		b.WriteString(sc.Path)
		b.WriteString("\n\n")

		// Trigger + description blockquote. Always include the triggers line
		// (even with empty globs list) so the section shape is predictable;
		// description is optional on its own line.
		b.WriteString("> Triggers: ")
		b.WriteString(strings.Join(sc.Globs, ", "))
		b.WriteString("\n")
		if desc := strings.TrimSpace(sc.Description); desc != "" {
			b.WriteString("> ")
			b.WriteString(desc)
			b.WriteString("\n")
		}
		b.WriteString("\n")

		body := strings.TrimSpace(sc.Document.Body)
		if body != "" {
			b.WriteString(body)
			b.WriteString("\n")
		}

		src := relAgentsMDSource(proj, sc.Document.SourcePath)
		if src != "" {
			sources = append(sources, src)
		}

		// AGENTS.md has no native scope enforcement — note this on every scope.
		warnings = append(warnings, plugin.Warning{
			Source:   src,
			Message:  "loaded always — AGENTS.md has no scope enforcement",
			Severity: "info",
		})
	}

	// 3. Skills. Sorted by Name.
	skills := make([]*model.Skill, 0, len(proj.Skills))
	for _, s := range proj.Skills {
		if s == nil {
			continue
		}
		skills = append(skills, s)
	}
	sort.SliceStable(skills, func(i, j int) bool {
		return skills[i].Name < skills[j].Name
	})
	if len(skills) > 0 {
		b.WriteString("\n---\n\n")
		b.WriteString("## Skills\n\n")
		for _, s := range skills {
			b.WriteString("### ")
			b.WriteString(s.Name)
			b.WriteString("\n\n")

			// Lead blockquote: description (or trigger fallback), globs,
			// script count if present.
			tagline := strings.TrimSpace(s.Description)
			if tagline == "" {
				tagline = strings.TrimSpace(s.Trigger)
			}
			if tagline != "" {
				b.WriteString("> ")
				b.WriteString(tagline)
				b.WriteString("\n")
			}
			if len(s.Globs) > 0 {
				b.WriteString("> Triggers: ")
				b.WriteString(strings.Join(s.Globs, ", "))
				b.WriteString("\n")
			}
			if len(s.Scripts) > 0 {
				fmt.Fprintf(&b, "> Scripts: %d (not executable from AGENTS.md-only tools)\n", len(s.Scripts))
			}
			b.WriteString("\n")

			if s.Document != nil {
				body := strings.TrimSpace(s.Document.Body)
				if body != "" {
					b.WriteString(body)
					b.WriteString("\n\n")
				}
				if src := relAgentsMDSource(proj, s.Document.SourcePath); src != "" {
					sources = append(sources, src)
				}
			}

			src := ""
			if s.Document != nil {
				src = relAgentsMDSource(proj, s.Document.SourcePath)
			}
			warnings = append(warnings, plugin.Warning{
				Source:   src,
				Message:  "loaded always — AGENTS.md has no skill scope enforcement; scripts cannot execute.",
				Severity: "info",
			})
		}
	}

	// 4. Slash commands. Sorted by Name.
	commands := make([]*model.Command, 0, len(proj.Commands))
	for _, c := range proj.Commands {
		if c == nil {
			continue
		}
		commands = append(commands, c)
	}
	sort.SliceStable(commands, func(i, j int) bool {
		return commands[i].Name < commands[j].Name
	})
	if len(commands) > 0 {
		b.WriteString("\n---\n\n")
		b.WriteString("## Slash commands\n\n")
		for _, c := range commands {
			b.WriteString("### /")
			b.WriteString(c.Name)
			b.WriteString("\n\n")

			if desc := strings.TrimSpace(c.Description); desc != "" {
				b.WriteString("> ")
				b.WriteString(desc)
				b.WriteString("\n")
			}
			b.WriteString("\n")

			if c.Document != nil {
				body := strings.TrimSpace(c.Document.Body)
				if body != "" {
					b.WriteString(body)
					b.WriteString("\n\n")
				}
				if src := relAgentsMDSource(proj, c.Document.SourcePath); src != "" {
					sources = append(sources, src)
				}
			}

			src := ""
			if c.Document != nil {
				src = relAgentsMDSource(proj, c.Document.SourcePath)
			}
			warnings = append(warnings, plugin.Warning{
				Source:   src,
				Message:  "documented as text; AGENTS.md-only tools cannot invoke as a command.",
				Severity: "info",
			})
		}
	}

	// 5. Subagents. Sorted by Name.
	agents := make([]*model.Agent, 0, len(proj.Agents))
	for _, a := range proj.Agents {
		if a == nil {
			continue
		}
		agents = append(agents, a)
	}
	sort.SliceStable(agents, func(i, j int) bool {
		return agents[i].Name < agents[j].Name
	})
	if len(agents) > 0 {
		b.WriteString("\n---\n\n")
		b.WriteString("## Subagents\n\n")
		for _, a := range agents {
			b.WriteString("### @")
			b.WriteString(a.Name)
			b.WriteString("\n\n")

			if desc := strings.TrimSpace(a.Description); desc != "" {
				b.WriteString("> ")
				b.WriteString(desc)
				b.WriteString("\n")
			}
			b.WriteString("\n")

			if a.Document != nil {
				body := strings.TrimSpace(a.Document.Body)
				if body != "" {
					b.WriteString(body)
					b.WriteString("\n\n")
				}
				if src := relAgentsMDSource(proj, a.Document.SourcePath); src != "" {
					sources = append(sources, src)
				}
			}

			src := ""
			if a.Document != nil {
				src = relAgentsMDSource(proj, a.Document.SourcePath)
			}
			warnings = append(warnings, plugin.Warning{
				Source:   src,
				Message:  "documented as text; AGENTS.md-only tools cannot dispatch to subagents.",
				Severity: "info",
			})
		}
	}

	// 6. Hooks. Preserve declaration order — events fire in event-order, not
	// alphabetical, and reshuffling would mislead readers.
	hooks := make([]*model.Hook, 0, len(proj.Hooks))
	for _, h := range proj.Hooks {
		if h == nil {
			continue
		}
		hooks = append(hooks, h)
	}
	if len(hooks) > 0 {
		b.WriteString("\n---\n\n")
		b.WriteString("## Hooks\n\n")
		b.WriteString("Documented for transparency; AGENTS.md-only tools cannot execute hooks.\n\n")
		for _, h := range hooks {
			b.WriteString("- **")
			b.WriteString(h.Event)
			b.WriteString("**")
			if m := strings.TrimSpace(h.Matcher); m != "" {
				b.WriteString(" matcher `")
				b.WriteString(m)
				b.WriteString("`")
			}
			b.WriteString(": ")
			b.WriteString(h.ScriptPath)
			b.WriteString("\n")

			if src := relAgentsMDSource(proj, h.ScriptPath); src != "" {
				sources = append(sources, src)
			}
			warnings = append(warnings, plugin.Warning{
				Source:   h.ScriptPath,
				Message:  "documented as text; AGENTS.md-only tools cannot execute hooks.",
				Severity: "info",
			})
		}
	}

	// 7. Permissions. Only emit a section if at least one list is non-empty;
	// an empty Permissions struct contributes no useful content.
	if proj.Permissions != nil && (len(proj.Permissions.Allow) > 0 || len(proj.Permissions.Deny) > 0 || len(proj.Permissions.Ask) > 0) {
		b.WriteString("\n---\n\n")
		b.WriteString("## Permissions\n\n")
		b.WriteString("Documented for transparency; AGENTS.md-only tools cannot enforce permissions.\n\n")
		if len(proj.Permissions.Allow) > 0 {
			b.WriteString("- Allow: ")
			b.WriteString(strings.Join(proj.Permissions.Allow, ", "))
			b.WriteString("\n")
		}
		if len(proj.Permissions.Deny) > 0 {
			b.WriteString("- Deny: ")
			b.WriteString(strings.Join(proj.Permissions.Deny, ", "))
			b.WriteString("\n")
		}
		if len(proj.Permissions.Ask) > 0 {
			b.WriteString("- Ask: ")
			b.WriteString(strings.Join(proj.Permissions.Ask, ", "))
			b.WriteString("\n")
		}

		// Permissions.yaml is the canonical source. Include it if the engine
		// has populated permissions and the file exists at the conventional
		// path; we don't have a SourcePath field on Permissions so we add
		// the conventional name relative to .agents/.
		sources = append(sources, "permissions.yaml")
		warnings = append(warnings, plugin.Warning{
			Source:   "permissions.yaml",
			Message:  "documented as text; AGENTS.md-only tools cannot enforce permissions.",
			Severity: "info",
		})
	}

	// 8. MCP servers. Sorted by Name for stable output.
	mcps := make([]*model.MCPServer, 0, len(proj.MCP))
	for _, m := range proj.MCP {
		if m == nil {
			continue
		}
		mcps = append(mcps, m)
	}
	sort.SliceStable(mcps, func(i, j int) bool {
		return mcps[i].Name < mcps[j].Name
	})
	if len(mcps) > 0 {
		b.WriteString("\n---\n\n")
		b.WriteString("## MCP servers\n\n")
		b.WriteString("Documented for transparency. Configure these in your tool's MCP setup.\n\n")
		for _, m := range mcps {
			b.WriteString("- **")
			b.WriteString(m.Name)
			b.WriteString("**: ")
			if u := strings.TrimSpace(m.URL); u != "" {
				b.WriteString("`")
				b.WriteString(u)
				b.WriteString("`")
			} else {
				b.WriteString("`")
				b.WriteString(m.Command)
				if len(m.Args) > 0 {
					b.WriteString(" ")
					b.WriteString(strings.Join(m.Args, " "))
				}
				b.WriteString("`")
			}
			b.WriteString("\n")

			warnings = append(warnings, plugin.Warning{
				Source:   "mcp.yaml",
				Message:  "documented as text; AGENTS.md-only tools must configure MCP separately.",
				Severity: "info",
			})
		}
		// mcp.yaml is the canonical source for the whole block.
		sources = append(sources, "mcp.yaml")
	}

	op := plugin.Operation{
		Kind:     plugin.OpWrite,
		Path:     "AGENTS.md",
		Content:  b.String(),
		Mode:     plugin.ModeWrite,
		Sources:  sources,
		Plugin:   "agents-md",
		Warnings: warnings,
	}

	return []plugin.Operation{op}, nil
}

// relAgentsMDSource returns the tagged source path for abs (project: or global:),
// or empty if abs is empty.
func relAgentsMDSource(proj *model.Project, abs string) string {
	return proj.SourceTag(abs)
}

// Compile-time check that AgentsMDPlugin satisfies plugin.Plugin.
var _ plugin.Plugin = (*AgentsMDPlugin)(nil)
