// Package v2 holds the autogenerated Draft 2020-12 JSON Schemas for the
// v0.9 canonical model. The actual schema files (*.schema.json) are
// produced by `go run ./cmd/prism-schema -out schema/v2`; this Go file
// exists solely to host the //go:generate directive and to make
// `schema/v2/` a valid Go package so `go generate ./...` picks it up.
//
// To regenerate after editing internal/model/model.go:
//
//	go generate ./...
//
// See SPEC §9.1 for the canonical schema layout.
package v2

//go:generate go run ../../cmd/prism-schema -out .
