package engine

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const defaultContext = "# Project context\n\nDescribe your project here.\n"

func initProject(opts Options, importFrom string) error {
	if opts.Root == "" {
		return fmt.Errorf("engine: Options.Root is required")
	}
	if opts.Registry == nil {
		return fmt.Errorf("engine: Options.Registry is required")
	}

	agentsDir := filepath.Join(opts.Root, ".agents")
	if _, err := os.Stat(agentsDir); err == nil {
		return fmt.Errorf("engine: .agents/ already exists at %s", agentsDir)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("engine: stat .agents/: %w", err)
	}

	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return fmt.Errorf("engine: mkdir %s: %w", agentsDir, err)
	}

	var created []string
	createFile := func(rel string, content []byte) error {
		full := filepath.Join(agentsDir, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(full, content, 0o644); err != nil {
			return err
		}
		created = append(created, filepath.Join(".agents", rel))
		return nil
	}

	// 1. Root context.md (possibly imported).
	rootBody := []byte(defaultContext)
	if importFrom == "claude" {
		claudePath := filepath.Join(opts.Root, "CLAUDE.md")
		if data, err := os.ReadFile(claudePath); err == nil {
			rootBody = data
		} else if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("engine: read CLAUDE.md: %w", err)
		}
	}
	if err := createFile("context.md", rootBody); err != nil {
		return err
	}

	// 2. Nested imports from CLAUDE.md files (skip root, which we already did).
	if importFrom == "claude" {
		err := filepath.WalkDir(opts.Root, func(path string, d fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if d.IsDir() {
				name := d.Name()
				// Skip vendored / hidden directories that shouldn't contain context.
				if path != opts.Root && (name == ".git" || name == ".agents" || name == "node_modules" || name == "vendor") {
					return filepath.SkipDir
				}
				return nil
			}
			if d.Name() != "CLAUDE.md" {
				return nil
			}
			if filepath.Dir(path) == opts.Root {
				return nil
			}
			rel, err := filepath.Rel(opts.Root, filepath.Dir(path))
			if err != nil {
				return err
			}
			data, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("engine: read %s: %w", path, err)
			}
			return createFile(filepath.Join(rel, "context.md"), data)
		})
		if err != nil {
			return err
		}
	}

	// 3. agents.config.yaml with autodetected targets.
	var targets []string
	for _, p := range opts.Registry.All() {
		if p.Detect(opts.Root) {
			targets = append(targets, p.Name())
		}
	}
	sort.Strings(targets)
	cfg := buildConfigYAML(targets)
	if err := createFile("agents.config.yaml", []byte(cfg)); err != nil {
		return err
	}

	if !opts.Quiet {
		fmt.Println("Initialized .agents/:")
		sort.Strings(created)
		for _, c := range created {
			fmt.Printf("  created %s\n", c)
		}
	}
	return nil
}

func buildConfigYAML(targets []string) string {
	var b strings.Builder
	b.WriteString("# .agents/agents.config.yaml — generated by `agents init`\n")
	b.WriteString("targets:\n")
	if len(targets) == 0 {
		b.WriteString("  []\n")
	} else {
		for _, t := range targets {
			b.WriteString("  - ")
			b.WriteString(t)
			b.WriteString("\n")
		}
	}
	b.WriteString("target_options: {}\n")
	return b.String()
}
