package importer

import (
	"errors"
	"path/filepath"
	"strings"
	"testing"
)

// TestAgentsMD_Empty: empty root → ErrSourceNotPresent.
func TestAgentsMD_Empty(t *testing.T) {
	root := t.TempDir()
	_, _, err := NewAgentsMD().Import(root)
	if !errors.Is(err, ErrSourceNotPresent) {
		t.Fatalf("Import on empty root: err = %v, want ErrSourceNotPresent", err)
	}
}

// TestAgentsMD_Detect verifies the v0.6 O(1) Detect contract: only root
// AGENTS.md and .github/AGENTS.md are recognized; nested-only layouts no
// longer auto-detect (users with that shape must pass --from agents-md
// explicitly). The old behavior walked the entire tree on every Detect
// call, which dominated `agents init --from auto` in large monorepos.
func TestAgentsMD_Detect(t *testing.T) {
	imp := NewAgentsMD()

	if imp.Detect(t.TempDir()) {
		t.Errorf("Detect on empty root returned true")
	}

	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "AGENTS.md"), "body")
	if !imp.Detect(root) {
		t.Errorf("Detect with root AGENTS.md returned false")
	}

	githubRoot := t.TempDir()
	mustWrite(t, filepath.Join(githubRoot, ".github", "AGENTS.md"), "github body")
	if !imp.Detect(githubRoot) {
		t.Errorf("Detect with .github/AGENTS.md returned false")
	}

	// v0.6: nested-only is intentionally NOT detected to keep Detect O(1).
	nestedOnly := t.TempDir()
	mustWrite(t, filepath.Join(nestedOnly, "pkg", "AGENTS.md"), "nested")
	if imp.Detect(nestedOnly) {
		t.Errorf("Detect with nested-only AGENTS.md returned true; v0.6 Detect is O(1) and should not walk the tree")
	}
}

// TestAgentsMD_BasicImport: root + nested copy whole bodies as
// context.md / scope context.md respectively.
func TestAgentsMD_BasicImport(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "AGENTS.md"), "# Project\nRoot body.\n")
	mustWrite(t, filepath.Join(root, "pkg", "auth", "AGENTS.md"), "Auth scope body.\n")

	proj, warnings, err := NewAgentsMD().Import(root)
	if err != nil {
		t.Fatalf("Import: %v", err)
	}
	if len(warnings) != 0 {
		t.Errorf("unexpected warnings: %+v", warnings)
	}

	if proj.Context == nil {
		t.Fatalf("proj.Context is nil")
	}
	if !strings.Contains(proj.Context.Body, "Root body.") {
		t.Errorf("context body missing expected text:\n%s", proj.Context.Body)
	}
	if !strings.Contains(proj.Context.Body, "<!-- imported from agents-md:") {
		t.Errorf("context body missing provenance comment:\n%s", proj.Context.Body)
	}

	if len(proj.Scopes) != 1 {
		t.Fatalf("len(proj.Scopes) = %d, want 1", len(proj.Scopes))
	}
	if proj.Scopes[0].Path != "pkg/auth" {
		t.Errorf("scope.Path = %q, want pkg/auth", proj.Scopes[0].Path)
	}
	if !strings.Contains(proj.Scopes[0].Document.Body, "Auth scope body.") {
		t.Errorf("scope body missing expected text:\n%s", proj.Scopes[0].Document.Body)
	}
}

// TestAgentsMD_HeuristicWarning: file beginning with the
// "Generated by agents." header should be SKIPPED with a warning, to
// prevent round-trip from a prism-managed repo.
func TestAgentsMD_HeuristicWarning(t *testing.T) {
	root := t.TempDir()
	generated := `<!-- Generated by agents. Do not edit by hand; edit .agents/ instead. -->

This is a prism-generated AGENTS.md.
`
	mustWrite(t, filepath.Join(root, "AGENTS.md"), generated)

	proj, warnings, err := NewAgentsMD().Import(root)
	if err != nil {
		t.Fatalf("Import: %v", err)
	}
	if proj.Context != nil {
		t.Errorf("proj.Context should be nil for a generated AGENTS.md; got %+v", proj.Context)
	}
	var found bool
	for _, w := range warnings {
		if strings.Contains(w.Heuristic, "generated-header") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected a warning about the generated-header skip; got %+v", warnings)
	}
}
