// agentsmd.go: imports AGENTS.md files (root + nested per the AGENTS.md
// spec's "nearest file wins" semantic) into the canonical
// *model.Project shape.
//
// The AGENTS.md spec is intentionally section-flexible, so we do NOT
// parse section headers — the whole body becomes the context document.
// To prevent round-trip from a prism-managed repo, any AGENTS.md that
// begins with the "<!-- Generated by agents." header from
// plugins/agentsmd.go is skipped.

package importer

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"

	"agents.dev/agents/internal/model"
	"agents.dev/agents/internal/scope"
)

// AgentsMDImporter reads AGENTS.md files (root + nested).
type AgentsMDImporter struct{}

// NewAgentsMD constructs an AgentsMDImporter.
func NewAgentsMD() *AgentsMDImporter { return &AgentsMDImporter{} }

// Name returns "agents-md".
func (i *AgentsMDImporter) Name() string { return "agents-md" }

// Detect returns true when a discoverable AGENTS.md marker exists at the
// project root. v0.6 makes this an O(1) stat check — earlier versions
// walked the entire tree on every Detect call, which dominated
// `agents init --from auto` runtime in large monorepos. Nested-only
// layouts no longer activate via Detect; users with that shape must
// pass `--from agents-md` explicitly. Import (below) still walks the
// tree to gather nested AGENTS.md files once activated.
func (i *AgentsMDImporter) Detect(root string) bool {
	if fi, err := os.Stat(filepath.Join(root, "AGENTS.md")); err == nil && !fi.IsDir() {
		return true
	}
	// Common alternative location for monorepos that keep agent docs
	// under .github/ alongside other meta files.
	if fi, err := os.Stat(filepath.Join(root, ".github", "AGENTS.md")); err == nil && !fi.IsDir() {
		return true
	}
	return false
}

// Import reads root and produces the canonical Project.
func (i *AgentsMDImporter) Import(root string) (*model.Project, []Warning, error) {
	if !i.Detect(root) {
		return nil, nil, ErrSourceNotPresent
	}

	proj := &model.Project{}
	var warnings []Warning

	// Root AGENTS.md.
	rootPath := filepath.Join(root, "AGENTS.md")
	if data, err := os.ReadFile(rootPath); err == nil {
		if hasGeneratedHeader(data) {
			warnings = append(warnings, Warning{
				SourcePath: "AGENTS.md",
				Heuristic:  "file starts with the agents.dev generated-header marker; skipping to prevent self-import loop",
				Severity:   "info",
			})
		} else {
			proj.Context = &model.Document{
				SourcePath: rootPath,
				Body:       provenanceComment("agents-md", rootPath) + string(data),
			}
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, nil, fmt.Errorf("agents-md: read %s: %w", rootPath, err)
	}

	// Nested AGENTS.md.
	walkErr := filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			name := d.Name()
			if path != root {
				if _, skip := skippedDirs[name]; skip {
					return filepath.SkipDir
				}
			}
			return nil
		}
		// v2 additive: also recognize AGENTS.override.md so the importer
		// can round-trip the IsOverride flag (SPEC §4.7.2). Filename match
		// is exact; both forms are nested-only (root override is not
		// surfaced as a Scope — it would belong in proj.Context, which we
		// leave to the canonical AGENTS.md for now).
		name := d.Name()
		isOverride := false
		switch name {
		case "AGENTS.md":
			// canonical, IsOverride stays false
		case "AGENTS.override.md":
			isOverride = true
		default:
			return nil
		}
		if filepath.Dir(path) == root {
			return nil
		}
		rel, err := filepath.Rel(root, filepath.Dir(path))
		if err != nil {
			return err
		}
		relSlash := filepath.ToSlash(rel)

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("agents-md: read %s: %w", path, err)
		}
		if hasGeneratedHeader(data) {
			warnings = append(warnings, Warning{
				SourcePath: relSlash + "/" + name,
				Heuristic:  "file starts with the agents.dev generated-header marker; skipping to prevent self-import loop",
				Severity:   "info",
			})
			return nil
		}
		// v2 additive (SPEC §4.7.2):
		//   - Name: slug derived from the scope path so downstream tools
		//     have a stable identifier even when Path contains slashes.
		//   - Activation: Cascade for nested AGENTS.md (the only mode this
		//     plugin natively expresses — SPEC §12 marks Cascade=N for agm
		//     and other modes Unsupported/Degraded).
		//   - IsOverride: true when the source filename is
		//     AGENTS.override.md (read-only round-trip; emission still
		//     consolidates into a single AGENTS.md per the Phase 2a note
		//     in plugins/agentsmd.go).
		//   - Extensions["agentsmd"]: opaque per-plugin namespace; empty
		//     for now (AGENTS.md has no frontmatter), reserved for v1.1
		//     when Tags/Description frontmatter lands.
		proj.Scopes = append(proj.Scopes, &model.Scope{
			Path:     relSlash,
			Globs:    scope.DefaultGlobs(relSlash),
			Priority: model.PriorityNormal,
			Document: &model.Document{
				SourcePath: path,
				Body:       provenanceComment("agents-md", path) + string(data),
			},
			Name:       slugifyName(relSlash),
			Activation: model.ScopeActivationCascade,
			IsOverride: isOverride,
			Extensions: map[string]any{"agentsmd": map[string]any{}},
		})
		return nil
	})
	if walkErr != nil {
		return nil, nil, walkErr
	}
	sort.Slice(proj.Scopes, func(a, b int) bool { return proj.Scopes[a].Path < proj.Scopes[b].Path })

	return proj, warnings, nil
}

// Compile-time check that *AgentsMDImporter implements Importer.
var _ Importer = (*AgentsMDImporter)(nil)
