// agentsmd.go: imports AGENTS.md files (root + nested per the AGENTS.md
// spec's "nearest file wins" semantic) into the canonical
// *model.Project shape.
//
// The AGENTS.md spec is intentionally section-flexible, so we do NOT
// parse section headers — the whole body becomes the context document.
// To prevent round-trip from a prism-managed repo, any AGENTS.md that
// begins with the "<!-- Generated by agents." header from
// plugins/agentsmd.go is skipped.

package importer

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"

	"agents.dev/agents/internal/model"
	"agents.dev/agents/internal/scope"
)

// AgentsMDImporter reads AGENTS.md files (root + nested).
type AgentsMDImporter struct{}

// NewAgentsMD constructs an AgentsMDImporter.
func NewAgentsMD() *AgentsMDImporter { return &AgentsMDImporter{} }

// Name returns "agents-md".
func (i *AgentsMDImporter) Name() string { return "agents-md" }

// Detect returns true if any AGENTS.md exists at root (top-level only —
// nested-only setups still detect via the root walk during Import, but
// activation via `--from agents-md` requires a discoverable marker).
func (i *AgentsMDImporter) Detect(root string) bool {
	if fi, err := os.Stat(filepath.Join(root, "AGENTS.md")); err == nil && !fi.IsDir() {
		return true
	}
	// Also detect if any nested AGENTS.md exists — some monorepo layouts
	// keep only per-package AGENTS.md and no root one.
	found := false
	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			name := d.Name()
			if path != root {
				if _, skip := skippedDirs[name]; skip {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if d.Name() == "AGENTS.md" && filepath.Dir(path) != root {
			found = true
			return filepath.SkipAll
		}
		return nil
	})
	return found
}

// Import reads root and produces the canonical Project.
func (i *AgentsMDImporter) Import(root string) (*model.Project, []Warning, error) {
	if !i.Detect(root) {
		return nil, nil, ErrSourceNotPresent
	}

	proj := &model.Project{}
	var warnings []Warning

	// Root AGENTS.md.
	rootPath := filepath.Join(root, "AGENTS.md")
	if data, err := os.ReadFile(rootPath); err == nil {
		if hasGeneratedHeader(data) {
			warnings = append(warnings, Warning{
				SourcePath: "AGENTS.md",
				Heuristic:  "file starts with the agents.dev generated-header marker; skipping to prevent self-import loop",
				Severity:   "info",
			})
		} else {
			proj.Context = &model.Document{
				SourcePath: rootPath,
				Body:       provenanceComment("agents-md", rootPath) + string(data),
			}
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, nil, fmt.Errorf("agents-md: read %s: %w", rootPath, err)
	}

	// Nested AGENTS.md.
	walkErr := filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			name := d.Name()
			if path != root {
				if _, skip := skippedDirs[name]; skip {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if d.Name() != "AGENTS.md" {
			return nil
		}
		if filepath.Dir(path) == root {
			return nil
		}
		rel, err := filepath.Rel(root, filepath.Dir(path))
		if err != nil {
			return err
		}
		relSlash := filepath.ToSlash(rel)

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("agents-md: read %s: %w", path, err)
		}
		if hasGeneratedHeader(data) {
			warnings = append(warnings, Warning{
				SourcePath: relSlash + "/AGENTS.md",
				Heuristic:  "file starts with the agents.dev generated-header marker; skipping to prevent self-import loop",
				Severity:   "info",
			})
			return nil
		}
		proj.Scopes = append(proj.Scopes, &model.Scope{
			Path:     relSlash,
			Globs:    scope.DefaultGlobs(relSlash),
			Priority: model.PriorityNormal,
			Document: &model.Document{
				SourcePath: path,
				Body:       provenanceComment("agents-md", path) + string(data),
			},
		})
		return nil
	})
	if walkErr != nil {
		return nil, nil, walkErr
	}
	sort.Slice(proj.Scopes, func(a, b int) bool { return proj.Scopes[a].Path < proj.Scopes[b].Path })

	return proj, warnings, nil
}

// Compile-time check that *AgentsMDImporter implements Importer.
var _ Importer = (*AgentsMDImporter)(nil)
